In [2]:
import numpy as np


In [7]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [9]:
# More than one dimension

a2 = np.array([[1,2], [3,4]])
a2


[[1 2]
 [3 4]]


In [15]:
print(type(a2))
print(a2.shape)

<class 'numpy.ndarray'>
(2, 2)


In [17]:
aw = np.array([[1,2,3], [4,5,6]])
aw

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
b = aw.reshape(3,2)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [28]:
## Create an empty array 

x = np.empty([3, 10], dtype = int)
print(x)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [30]:
#Convert list to ndarray

x2 = [1,2,3]
print(x2)
a27 = np.asarray(x2)
print(a27)

[1, 2, 3]
[1 2 3]


In [34]:
#Calculation

ma = np.array([0,30,45,60,90])

print('Sine of different angles:')

#Convert to radians by multiplying to pi/180
print(np.sin(ma*np.pi/180))

Sine of different angles:
[0.         0.5        0.70710678 0.8660254  1.        ]


In [41]:
print('Cosine values for angles in array:')
print(np.cos(ma*np.pi/180))
print('\n')

Cosine values for angles in array:
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]




In [42]:
print('Tangent values for given angles:')
print(np.tan(ma*np.pi/180))

Tangent values for given angles:
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [44]:
ma2 = np.array([10, 30.1, 45.54444, 60.9, 90])
ma3 = np.array([10, 30.1, 45.5, 60.9, 90])

In [48]:
print(np.around(ma2))
print(np.around(ma2, decimals = 1))

[10. 30. 46. 61. 90.]
[10.  30.1 45.5 60.9 90. ]


In [50]:
print(np.floor(ma2))
print(np.ceil(ma2))

[10. 30. 45. 60. 90.]
[10. 31. 46. 61. 90.]


In [54]:
#Simple operations 

print(np.add(ma2, ma3))
print(np.subtract(ma2, ma3))
print(np.multiply(ma2, ma3))
print(np.divide(ma2, ma3))

[ 20.       60.2      91.04444 121.8     180.     ]
[0.      0.      0.04444 0.      0.     ]
[ 100.       906.01    2072.27202 3708.81    8100.     ]
[1.        1.        1.0009767 1.        1.       ]


## [Numpy Dot, Explained](https://www.sharpsightlabs.com/blog/numpy-dot/)


## [Numpy For DeepLearning]( https://towardsdatascience.com/all-the-numpy-you-need-to-supercharge-your-deep-learning-code-e7a22fe4ede2)

In [55]:
#Dot value

print( np.dot(ma2,ma3))

14887.09202


## Numpy - Matrix (other way of creating it)


In [56]:
import numpy.matlib


print(np.matlib.empty((2,2)))

[[5.77350269e-01 1.00000000e+00]
 [1.73205081e+00 1.63312394e+16]]


In [59]:
print(np.matlib.zeros((12,12)))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [64]:
print(np.matlib.ones((12,6)))

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [72]:
p = np.matlib.eye(n = 5, M = 5, dtype = float)
p

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [75]:
#Another option is to create using random function

print(np.matlib.rand(3,3))

[[0.99671068 0.4917375  0.01020143]
 [0.49371077 0.69652674 0.25516738]
 [0.11725133 0.67765705 0.00989713]]


In [84]:
i = np.matrix('1,2;3,4;8,9')
print(i)

[[1 2]
 [3 4]
 [8 9]]
